// NOTE: DO NOT EDIT, this file is generated by gendoc.sh.

/*
Package webadmin is a web app for the mox administrator for viewing and
changing the configuration, like creating/removing accounts, viewing DMARC and
TLS reports, check DNS records for a domain, change the webserver
configuration, etc.

# Admin API

The admin API uses the sherpa protocol at /admin/api/. All methods are called
via HTTP POST with a JSON body of the form {"params": [...]}, where params is
a positional JSON array matching the function signature.

HTTP Basic Authentication is supported for programmatic/script access, removing
the need for cookie and CSRF token management. The username is ignored; only
the admin password (configured in the admin password file) is checked.

HTTP response status 200 OK indicates a successful method call. The response
body is a JSON object with a "result" field on success, or an "error" field
with "code" and "message" on failure.

# Admin API examples

Below are examples for making admin API calls using HTTP Basic Auth with curl.
Replace "admin:moxadminpassword" with any username and your actual admin
password.

Check the server version:

	$ curl -s -u admin:moxadminpassword \
		-X POST -H 'Content-Type: application/json' \
		-d '{"params": []}' \
		http://localhost:1080/admin/api/Version
	{
		"result": ["dev", "linux", "amd64"]
	}

List all domains:

	$ curl -s -u admin:moxadminpassword \
		-X POST -H 'Content-Type: application/json' \
		-d '{"params": []}' \
		http://localhost:1080/admin/api/Domains
	{
		"result": [
			[{"Unicode": "example.com", "ASCII": "example.com"}],
			[]
		]
	}

Add a new domain with an initial account and postmaster address:

	$ curl -s -u admin:moxadminpassword \
		-X POST -H 'Content-Type: application/json' \
		-d '{"params": [false, "example.com", "postmaster", "postmaster"]}' \
		http://localhost:1080/admin/api/DomainAdd

Parameters: disabled (bool), domain (string), accountName (string), localpart (string).

Remove a domain:

	$ curl -s -u admin:moxadminpassword \
		-X POST -H 'Content-Type: application/json' \
		-d '{"params": ["example.com"]}' \
		http://localhost:1080/admin/api/DomainRemove

Add a new email account with an initial address:

	$ curl -s -u admin:moxadminpassword \
		-X POST -H 'Content-Type: application/json' \
		-d '{"params": ["john", "john@example.com"]}' \
		http://localhost:1080/admin/api/AccountAdd

Parameters: accountName (string), address (string).

Remove an email account:

	$ curl -s -u admin:moxadminpassword \
		-X POST -H 'Content-Type: application/json' \
		-d '{"params": ["john"]}' \
		http://localhost:1080/admin/api/AccountRemove

Set/reset the password for an email account (minimum 8 characters):

	$ curl -s -u admin:moxadminpassword \
		-X POST -H 'Content-Type: application/json' \
		-d '{"params": ["john", "newpassword123"]}' \
		http://localhost:1080/admin/api/SetPassword

List all accounts:

	$ curl -s -u admin:moxadminpassword \
		-X POST -H 'Content-Type: application/json' \
		-d '{"params": []}' \
		http://localhost:1080/admin/api/Accounts
	{
		"result": [["john", "postmaster"], []]
	}

Error responses include a code for programmatic handling:

	$ curl -s -u admin:moxadminpassword \
		-X POST -H 'Content-Type: application/json' \
		-d '{"params": ["nonexistent"]}' \
		http://localhost:1080/admin/api/AccountRemove
	{
		"error": {"code": "user:error", "message": "removing account: account does not exist"}
	}

Authentication failure (wrong password) returns HTTP 401:

	$ curl -s -u admin:wrongpassword \
		-X POST -H 'Content-Type: application/json' \
		-d '{"params": []}' \
		http://localhost:1080/admin/api/Version
	401 - unauthorized
*/
package webadmin

// NOTE: DO NOT EDIT, this file is generated by gendoc.sh.
